---
- name: Remove akregator*
  dnf:
    state: absent
    autoremove: true
    name:
      - akregator*
      
- name: Remove firefox*
  dnf:
    state: absent
    autoremove: true
    name:
      - firefox*

- name: Remove kdepim*
  dnf:
    state: absent
    autoremove: true
    name:
      - kdepim*

- name: Remove libreoffice*
  dnf:
    state: absent
    autoremove: true
    name:
      - libreoffice*

- name: Remove more unwanted default packages
  dnf:
    state: absent
    autoremove: true
    name:
      - dragon
      - kcalc
      - kwrite
      - neochat
      - okular
      - toolbox

- name: Install Group packages
  dnf:
    state: present
    name:
      - "@virtualization"

- name: Install General Utilities
  dnf:
    state: present
    name:
      - 7zip
      - android-tools
      - bleachbit
      - calibre
      - conda
      - corectrl
      - displaycal
      - distrobox
      - fastfetch
      - fish
      - gtk3-devel
      - libva-utils
      - pidgin
      - pidgin-otr
      - snapd
      - tldr
      - zsh

- name: Install Browsers
  dnf:
    state: present
    name:
      - google-chrome-stable
      - microsoft-edge-stable

- name: Install Multimedia
  dnf:
    state: present
    name:
      - clementine

- name: Install Development Tools
  dnf:
    state: present
    name:
      - gh
      - git-lfs
      - godot
      - nix
      - nix-daemon

- name: Install 3D Printing
  dnf:
    state: present
    name:
      - prusa-slicer

- name: Install KDE Apps
  dnf:
    state: present
    name:
      - dolphin-plugins
      - kate
      - kclock
      - kcron
      - kmousetool
      - kompare
      - krename
      - krusader
      - ksystemlog
      - ktimer
      - nextcloud-client-dolphin

- name: Install Container Tools
  dnf:
    state: present
    name:
      - buildah
      - flatpak-builder
      - skopeo

- name: Install Virtualization & Dev
  dnf:
    state: present
    name:
      - ansible
      - ansible-collection-community-general
      - gnome-boxes
      - incus-*
      - libguestfs
      - libguestfs-tools-c
      - podman*
      - qemu-img
      - swtpm
      - vagrant
      - vagrant-libvirt

- name: Install Cockpit
  dnf:
    state: present
    name:
      - cockpit-*

- name: Install Networking & VPN
  dnf:
    state: present
    name:
      - proton-vpn-cli
      - proton-vpn-gnome-desktop
      - protonvpn-stable-release

- name: Install Security
  dnf:
    state: present
    name:
      - fail2ban
      - fail2ban-firewalld
      - fail2ban-systemd

- name: Install Communication
  dnf:
    state: present
    name:
      - zoom

- name: Install Fonts
  dnf:
    state: present
    name:
      - google-noto-color-emoji-fonts
      - google-noto-fonts-all
      - rsms-inter-fonts
