- name: Copy XML to temp location
  copy:
    src: "{{ current_file.path }}"
    dest: "/tmp/{{ current_file.path | basename }}"

- name: Remove UUID from temp file
  lineinfile:
    path: "/tmp/{{ current_file.path | basename }}"
    regexp: '<uuid>.*</uuid>'
    state: absent

- name: Remove MAC address from temp file
  lineinfile:
    path: "/tmp/{{ current_file.path | basename }}"
    regexp: "<mac address=.*/>"
    state: absent

- name: Define VM from sanitized XML
  command: virsh define "/tmp/{{ current_file.path | basename }}"

- name: Remove temp file
  file:
    path: "/tmp/{{ current_file.path | basename }}"
    state: absent
